const express=require("express");
const http=require("http");
const path=require("path");
const fs=require("fs");
const crypto=require("crypto");
const cookieParser=require("cookie-parser");
const {Server}=require("socket.io");
const admin=require("firebase-admin");
const db=require("./database/db");
const {getPaymentProvider}=require("./backend/payment_gateway/payment_processor");
const workflow=require("./backend/workflow/order_workflow");
const {rankProviders}=require("./backend/dispatch_engine/ranking");
const {ROLE_PERMISSIONS,STATUS_FLOW,transitions,canTransition,transitionAllowed,hasPermission}=workflow;const parseCoords=workflow.parseCoords||require("./backend/dispatch_engine/ranking").parseCoords;
const serviceMatches=require("./backend/dispatch_engine/ranking").serviceMatches;
const distance=require("./backend/dispatch_engine/ranking").distance;const express=require("express");
const http=require("http");
const path=require("path");
const fs=require("fs");
const crypto=require("crypto");
const cookieParser=require("cookie-parser");
const {Server}=require("socket.io");
const admin=require("firebase-admin");
const db=require("./database/db");
const {getPaymentProvider}=require("./backend/payment_gateway/payment_processor");
const workflow=require("./backend/workflow/order_workflow");
const {rankProviders}=require("./backend/dispatch_engine/ranking");
const {ROLE_PERMISSIONS,STATUS_FLOW,transitions,canTransition,transitionAllowed,hasPermission}=workflow;const parseCoords=workflow.parseCoords||require("./backend/dispatch_engine/ranking").parseCoords;
const serviceMatches=require("./backend/dispatch_engine/ranking").serviceMatches;
const distance=require("./backend/dispatch_engine/ranking").distance;const express=require("express");
const http=require("http");
const path=require("path");
const fs=require("fs");
const crypto=require("crypto");
const cookieParser=require("cookie-parser");
const {Server}=require("socket.io");
const admin=require("firebase-admin");
const db=require("./database/db");
const {getPaymentProvider}=require("./backend/payment_gateway/payment_processor");
const workflow=require("./backend/workflow/order_workflow");
const {rankProviders}=require("./backend/dispatch_engine/ranking");
const {ROLE_PERMISSIONS,STATUS_FLOW,transitions,canTransition,transitionAllowed,hasPermission}=workflow;const parseCoords=workflow.parseCoords||require("./backend/dispatch_engine/ranking").parseCoords;
const serviceMatches=require("./backend/dispatch_engine/ranking").serviceMatches;
const distance=require("./backend/dispatch_engine/ranking").distance;const express=require("express");
const http=require("http");
const path=require("path");
const fs=require("fs");
const crypto=require("crypto");
const cookieParser=require("cookie-parser");
const {Server}=require("socket.io");
const admin=require("firebase-admin");
const db=require("./database/db");
const {getPaymentProvider}=require("./backend/payment_gateway/payment_processor");
const workflow=require("./backend/workflow/order_workflow");
const {rankProviders}=require("./backend/dispatch_engine/ranking");
const {ROLE_PERMISSIONS,STATUS_FLOW,transitions,canTransition,transitionAllowed,hasPermission}=workflow;const parseCoords=workflow.parseCoords||require("./backend/dispatch_engine/ranking").parseCoords;
const serviceMatches=require("./backend/dispatch_engine/ranking").serviceMatches;
const distance=require("./backend/dispatch_engine/ranking").distance;
